//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZAsesAutoType.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ases.noncd.rz.db.de/SES/html?ClientNo=06")]
        public string ASESBaseUrl {
            get {
                return ((string)(this["ASESBaseUrl"]));
            }
            set {
                this["ASESBaseUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ChangeIt!")]
        public string ASESUserId {
            get {
                return ((string)(this["ASESUserId"]));
            }
            set {
                this["ASESUserId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ChangeIt!")]
        public string ASESPassword {
            get {
                return ((string)(this["ASESPassword"]));
            }
            set {
                this["ASESPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("06-DB-Systel")]
        public string ASESClient {
            get {
                return ((string)(this["ASESClient"]));
            }
            set {
                this["ASESClient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\n<ArrayOfString xmlns:xsd=\"http://www.w3.o" +
            "rg/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n  <str" +
            "ing>01-Zentrale Cargo</string>\n  <string>02-Erfurt Test</string>\n  <string>03-DB" +
            " Konzernleitung</string>\n  <string>04-P-Zentrale</string>\n  <string>05-Ffm/Fernv" +
            "erk.</string>\n  <string>06-DB-Systel</string>\n  <string>07-Agv MoVe</string>\n  <" +
            "string>08-DB InfraGO BZ S-B. Berlin</string>\n  <string>09-Ffm/Karlstr.</string>\n" +
            "  <string>10-DB Sicherheit</string>\n  <string>11-Frankfurt Stephenson</string>\n " +
            " <string>12-TARIS-SST-Test</string>\n  <string>13-Hannover</string>\n  <string>14-" +
            "Hamburg</string>\n  <string>15-DB Systemtechnik</string>\n  <string>16-München</st" +
            "ring>\n  <string>17-Berlin sonstige</string>\n  <string>18-DB Regio</string>\n  <st" +
            "ring>19-Nürnberg</string>\n  <string>20-Wuppertal</string>\n  <string>21-DBS KT</s" +
            "tring>\n  <string>22-JobService</string>\n  <string>23-München Richelstr.</string>" +
            "\n  <string>24-Cargo Zentrale</string>\n  <string>25-FTZ</string>\n  <string>26-Stu" +
            "ttgart</string>\n  <string>27-Saarbrücken</string>\n  <string>28-DB RegioNetz SOB<" +
            "/string>\n  <string>29-Witten Werk</string>\n  <string>30-DB Regio BWB</string>\n  " +
            "<string>31-Nürnberg Hbf</string>\n  <string>32-DB Immobilien</string>\n  <string>3" +
            "3-DB T/B</string>\n  <string>34-SSC Buchhaltung</string>\n  <string>35-Bildung</st" +
            "ring>\n  <string>36-KS Duisburg</string>\n  <string>37-Cargo NL Ffm</string>\n  <st" +
            "ring>38-Netz Ffm</string>\n  <string>39-DB Cargo-Werke</string>\n  <string>40-ICE-" +
            "BW München</string>\n  <string>41-R&amp;T Region</string>\n  <string>42-Gastronomi" +
            "e (DBG)</string>\n  <string>43-DB Energie</string>\n  <string>44-DBS Süd</string>\n" +
            "  <string>45-DB Regio Nord</string>\n  <string>46-DB Fernverkehr ICE</string>\n  <" +
            "string>47-DB Service</string>\n  <string>48-DB Sicherheit</string>\n  <string>49-D" +
            "B Stiftung</string>\n  <string>50-DB Vertrieb</string>\n  <string>51-DB Connect</s" +
            "tring>\n  <string>52-DB Fahrzeuginstandhaltung</string>\n  <string>53-DB Regio Mit" +
            "te</string>\n  <string>54-DB InfraGO AG (S&amp;S)</string>\n  <string>55-DB Regio " +
            "NO</string>\n  <string>56-DB E&amp;C</string>\n  <string>57-DB Regio Bayern</strin" +
            "g>\n  <string>58-DB Regio SO</string>\n  <string>59-DB Regio NRW</string>\n  <strin" +
            "g>60-DB Fern TL</string>\n  <string>61-DB Cargo</string>\n  <string>90-DB Personal" +
            "service</string>\n  <string>DB-Schulung</string>\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ASESClientList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ASESClientList"]));
            }
            set {
                this["ASESClientList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Deutsch")]
        public string ASESLanguage {
            get {
                return ((string)(this["ASESLanguage"]));
            }
            set {
                this["ASESLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\n<ArrayOfString xmlns:xsd=\"http://www.w3.o" +
            "rg/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n  <str" +
            "ing>Deutsch</string>\n  <string>English</string>\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ASESLanguageList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ASESLanguageList"]));
            }
            set {
                this["ASESLanguageList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("09:00")]
        public string ASESPunchInAM {
            get {
                return ((string)(this["ASESPunchInAM"]));
            }
            set {
                this["ASESPunchInAM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chrome")]
        public string WebDriver {
            get {
                return ((string)(this["WebDriver"]));
            }
            set {
                this["WebDriver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\n<ArrayOfString xmlns:xsd=\"http://www.w3.o" +
            "rg/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n  <str" +
            "ing>Chrome</string>\n  <string>Edge</string>\n  <string>Firefox</string>\n</ArrayOf" +
            "String>")]
        public global::System.Collections.Specialized.StringCollection WebDriverList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["WebDriverList"]));
            }
            set {
                this["WebDriverList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12:00")]
        public string ASESPunchOutAM {
            get {
                return ((string)(this["ASESPunchOutAM"]));
            }
            set {
                this["ASESPunchOutAM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12:00")]
        public string ASESPunchInPM {
            get {
                return ((string)(this["ASESPunchInPM"]));
            }
            set {
                this["ASESPunchInPM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17:00")]
        public string ASESPunchOutPM {
            get {
                return ((string)(this["ASESPunchOutPM"]));
            }
            set {
                this["ASESPunchOutPM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ASESDoLogin {
            get {
                return ((bool)(this["ASESDoLogin"]));
            }
            set {
                this["ASESDoLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ASESDoPunch {
            get {
                return ((bool)(this["ASESDoPunch"]));
            }
            set {
                this["ASESDoPunch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ASESDoLogout {
            get {
                return ((bool)(this["ASESDoLogout"]));
            }
            set {
                this["ASESDoLogout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int ASESPunchDeviation {
            get {
                return ((int)(this["ASESPunchDeviation"]));
            }
            set {
                this["ASESPunchDeviation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ASESUseSso {
            get {
                return ((bool)(this["ASESUseSso"]));
            }
            set {
                this["ASESUseSso"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ChangeIt!")]
        public string ASESSsoAccount {
            get {
                return ((string)(this["ASESSsoAccount"]));
            }
            set {
                this["ASESSsoAccount"] = value;
            }
        }
    }
}
